name = "PhaseFields"
uuid = "6af1007f-d462-454c-a7f3-5589aa52c87f"
authors = ["Hiroharu Sugawara <hsugawa@tmu.ac.jp>"]
version = "0.1.0"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
OpenCALPHAD = "f22b17f6-ccb9-4067-ab50-5d8cfb3cb77d"

[extensions]
GridapExt = "Gridap"
OpenCALPHADExt = "OpenCALPHAD"

[compat]
DiffEqCallbacks = "4"
DifferentiationInterface = "0.7"
ForwardDiff = "0.10"
Gridap = "0.17, 0.18"
OpenCALPHAD = "0.1"
OrdinaryDiffEq = "6"
SciMLBase = "2"
julia = "1.10"

[extras]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Gridap", "Test"]
